CREATE DATABASE mini_board;

USE mini_board;

CREATE TABLE board (

number INT PRIMARY KEY AUTO_INCREMENT
,title VARCHAR(100) NOT NULL
,detail VARCHAR(1000) NOT NULL
,Date_of_issue DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,Delete_flag CHAR(1) NOT NULL DEFAULT '0'
,Delete_date DATETIME DEFAULT NULL
);